Custom installation page
freshworks/marketplace-sample-apps pull request #203
Opened 2020-10-01 12:38 UTC by iyosayi

2020-10-02 01:50 UTC, Saif-Shines requested changes
Hi @iyosayi ,

Thank you for taking up effort to make a pull request on sample apps respositoy. I have only 1 thing to suggest,

Due to the nature of [Freshworks CLI](https://developers.freshdesk.com/v2/docs/freshworks-cli/) parsing `iparam.html`, it expects 3 methods to be inside of script tag in `iparams.html`

1. `postConfigs`
2. `getConfigs`
3. `validate`

Can you move these 3 functions alone from `iparams.js` and put them back under the script tag?

This is a small caveat from [custom installation page](https://developers.freshdesk.com/v2/docs/custom-installation-page/). Apart from that remaining all looks good and can be merged.

2020-10-05 09:13 UTC, Saif-Shines commented
@iyosayi Please le us know if you need any help :)

2020-10-05 09:15 UTC, iyosayi commented
> @iyosayi Please let us know if you need any help :)

I am on it already.

2020-10-05 09:35 UTC, Saif-Shines approved these changes

2020-10-05 09:36 UTC, merged