Reorganise: custom_installation page app
freshworks/marketplace-sample-apps pull request #213
Opened 2020-10-04 08:54 UTC by harish-sethuraman

2020-10-04 17:32 UTC, ravirajsubramanian requested changes

2020-10-04 17:32 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Configuration-Features/custom_installation_page_app/README.md
> + _requesting data from API_ | _Makes use of client.request_
@harish-sethuraman Thank you for stepping in to contribute! Cheers!

Could you add any of the features listed in the left sidebar from [the documentation](https://developer.freshdesk.com/v2/docs/quick-start)?
It would be clear if they were mentioned in the first column and the details that you have mentioned are added in the second column.

2020-10-04 17:58 UTC, harish-sethuraman commented on Freshworks-Samples/App-Development-Features/Configuration-Features/custom_installation_page_app/README.md
> + _requesting data from API_ | _Makes use of client.request_
Yea sure will do it

2020-10-04 18:03 UTC, harish-sethuraman commented
@ravirajsubramanian Is it okay now ?

2020-10-05 06:27 UTC, ravirajsubramanian approved these changes

2020-10-05 09:12 UTC, merged