fullcontact app added
freshworks/marketplace-sample-apps pull request #233
Opened 2020-10-22 17:13 UTC by sarfaraz187

2020-10-23 06:32 UTC, Saif-Shines approved these changes

2020-10-23 07:44 UTC, ravirajsubramanian requested changes
Please remove /app/freshchat_logo.png as it is not used in the app.

2020-10-23 07:44 UTC, ravirajsubramanian commented on Demo-Apps/fullcontact_app/app/app.js
> +    console.log(error);
Suggestion: Please use console.info or console.error statements to differentiate production logs from development logs, console.log statements.

2020-10-23 07:44 UTC, ravirajsubramanian commented on Demo-Apps/fullcontact_app/app/modal.html
> +</html>
Please add an empty line at the end-of-file.

2020-10-23 07:44 UTC, ravirajsubramanian commented on Demo-Apps/fullcontact_app/app/modal.html
> +</html>
Also, please follow the same for all the files.

2020-10-23 15:27 UTC, sarfaraz187 commented on Demo-Apps/fullcontact_app/app/app.js
> +    console.log(error);
Thanks for the suggestion @ravirajsubramanian . changes made as requested do review.

2020-10-23 15:28 UTC, sarfaraz187 commented on Demo-Apps/fullcontact_app/app/modal.html
> +</html>
Thanks for the suggestion @ravirajsubramanian . changes made as requested do review.

2020-10-24 14:27 UTC, ravirajsubramanian approved these changes

2020-10-24 14:27 UTC, merged

2020-10-24 14:40 UTC, sarfaraz187 commented
Thank you @Saif-Shines and @ravirajsubramanian for your support in building this App.

2020-10-24 14:49 UTC, ravirajsubramanian commented
Thank you to you for contributing to our repository. I hope it would have helped you as well.

If you have any feedback from your development experience, please share it with us on [our developer forum](community.developers.freshworks.com).