Fix defects in timer on tap app
freshworks/marketplace-sample-apps pull request #271
Opened 2020-10-30 04:56 UTC by mani-vandrangi

Fixed the following issues in timer_on_tap app

1. Updated README.md to add configs before testing
2. Fixed errors in FDK validate
3. Fixed bootstrap jquery dependency error
4. Fixed agents not showing error

2020-10-30 06:00 UTC, ravirajsubramanian requested changes

2020-10-30 06:00 UTC, ravirajsubramanian commented on Freshworks-Samples/Freshdesk/timer_on_tap/app/startTimer.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
Please remove the jQuery as it is not used anywhere. If used anywhere, please replace the function with Vanilla JS.

2020-10-30 06:20 UTC, ravirajsubramanian commented on Freshworks-Samples/Freshdesk/timer_on_tap/app/startTimer.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
This has been added as a separate issue #272. So, merging this PR.

2020-10-30 06:21 UTC, ravirajsubramanian approved these changes

2020-10-31 17:10 UTC, ravirajsubramanian approved these changes

2020-11-02 04:47 UTC, Saif-Shines approved these changes

2020-11-02 05:15 UTC, mani-vandrangi commented
Abandoning my PR as changes are already merged in another PR

2020-11-02 05:15 UTC, closed without merging

2020-11-02 13:16 UTC, ravirajsubramanian commented
These changes have been fixed in the PR #275.