Adding Custom Entities sample app
freshworks/marketplace-sample-apps pull request #282
Opened 2020-12-31 09:14 UTC by hemchander23

2021-01-05 11:38 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/README.md
> +![](https://user-images.githubusercontent.com/19341550/99782175-d36c7800-2b3e-11eb-9af4-463c943d5427.png)
Can we add the screenshot in the repo and use a relative path rather than 3rd party link that might break in the future?

2021-01-05 11:38 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/README.md
> +3. (For early access) Custom Entities might already be available for users who are part of the EAP. If you are interested please [feel free to request access here](https://community.developers.freshw
Can we make it general assuming it's already available for everyone?
The EAP registration is closed and it's already not useful. 🙂

2021-01-05 11:38 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/README.md
> +1. Make sure you have a trial [Freshdesk] account created.
Could you add a link to the website?

2021-01-05 11:38 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/README.md
> +2. Ensure that you have the latest version of the Freshworks Developer Kit (FDK) installed properly.
Could you add the documentation link?

2021-01-05 11:38 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/app.js
> +  return entity.get(entityName);
Could you handle the error here or where it is called from?

2021-01-05 11:38 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/app.js
> +    queryObj = Object.assign({}, queryObj, {
Since queryObj has been created by the same execution, this code can be simplified in the following way to remove the new assigning part.

`Object.assign(queryObj, { short_code });`

2021-01-05 11:38 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/app.js
> +}
Please add a new line at the EOF.

2021-01-05 11:38 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/calendar.js
> +function createCalendarEventObj(i) {
Can the argument be renamed to something meaningful? 😅

2021-01-05 11:38 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/util.js
> +      switch (data.message.action) {
If it doesn't have many cases and a default case, can this be converted to an `if` condition?

2021-01-07 04:43 UTC, raghuram-periaswamy requested changes

2021-01-07 04:43 UTC, raghuram-periaswamy commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/server/server.js
> +      appointmentRecords.then((i) => {
Let's provide some appropriate names over single letter variables.

> Applicable at other such instances as well.

2021-01-07 04:43 UTC, raghuram-periaswamy commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/server/server.js
> +          uObj.status = "3";
Status with `5` or `3` is hard to read. Shall we have an ENUM for better readability.

```js
const TICKET_STATUS = {
  pending: 3,
  closed: 5
};
```

> Applicable at other such instances as well.

```suggestion
          uObj.status = TICKET_STATUS.pending;
```

2021-01-07 04:43 UTC, raghuram-periaswamy commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/modal/restaurant.html
> +    /**
Let's have the JS in separate file for both `appointment` & `restaurant` modals.

2021-01-07 04:43 UTC, raghuram-periaswamy commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/modal/restaurant.html
> +        document.querySelector('#type_toast').trigger({ type: 'error', content: 'Check if all fields are filled' });
We use a combination of both toast and interface notification, probably let's use a single method.

2021-01-07 04:43 UTC, raghuram-periaswamy commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/modal/appointment.html
> +        })
```suggestion
      getRestaurantDetails()
        .then(createTicketForAppointment)
        .then(createAppointmentRecord)
        .then(updateRestaurantRecord)
```

2021-01-07 04:43 UTC, raghuram-periaswamy commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/modal/appointment.html
> +            var st = new Date(context.data.startAt);
This part is hard to be understood. If possible shall we use the standard date functions to yield the appropriate output or have comments on whats done here.

2021-01-07 04:43 UTC, raghuram-periaswamy commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/util.js
> +  switch (code) {
Switch is not really required. An ENUM object should work.

2021-01-07 04:43 UTC, raghuram-periaswamy commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/calendar.js
> +    backgroundColor: hashCode(i.appointment.data.restaurant_info),
What if multiple restaurants have the same name? Should we do it by id?

2021-01-11 06:38 UTC, hemchander23 commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/README.md
> +![](https://user-images.githubusercontent.com/19341550/99782175-d36c7800-2b3e-11eb-9af4-463c943d5427.png)
Sure

2021-01-19 05:40 UTC, hemchander23 commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/app.js
> +}
Sure

2021-01-19 05:49 UTC, hemchander23 commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/calendar.js
> +function createCalendarEventObj(i) {
modified the params 👍

2021-01-19 06:11 UTC, hemchander23 commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/calendar.js
> +    backgroundColor: hashCode(i.appointment.data.restaurant_info),
Hi Raghu, Do you mean to include the ID in the calendar event title?

2021-01-19 06:28 UTC, hemchander23 commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/modal/appointment.html
> +            var st = new Date(context.data.startAt);
Sure

2021-01-19 08:47 UTC, hemchander23 commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/util.js
> +      switch (data.message.action) {
Sure

2021-01-19 08:51 UTC, hemchander23 commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/server/server.js
> +          uObj.status = "3";
added

2021-01-21 10:57 UTC, ravirajsubramanian requested changes

2021-01-21 10:57 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/app.js
> +      $("#restaurant_list").html(generateRestaurantList(data.records));
Please replace it with Vanilla JS code here as jQuery has been removed from the imports. The following code would work. :)

`document.getElementById("restaurant_list").innerHTML = generateRestaurantList(data.records);`

2021-01-21 10:57 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/app.js
> +    $("#restaurant_list").html(generateRestaurantList(data.records));
Please replace this statement with Vanilla JS as suggested above.

2021-01-22 05:25 UTC, hemchander23 commented on Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/custom_entities/app/js/app.js
> +      $("#restaurant_list").html(generateRestaurantList(data.records));
Thanks Ravi. Removed

2021-01-22 05:39 UTC, ravirajsubramanian approved these changes

2021-01-22 10:41 UTC, raghuram-periaswamy approved these changes
+1

2021-01-22 11:21 UTC, hemchander23 commented
Thanks @raghuram-periaswamy @ravirajsubramanian !

2021-01-22 11:22 UTC, merged