Add: Config-Placeholders-Freshservice sample app
freshworks/marketplace-sample-apps pull request #311
Opened 2021-04-20 19:24 UTC by teja-kummarikuntla

A sample app for Freshservice presenting all the UI-enabled app locations with a placeholder.
The app locations are taken from the Freshservice developer documentation.

**App Locations:**
1. Global Navigation Pane
    - `full_page_app `
2. Ticket Details Page
    - `ticket_sidebar `
    - `ticket_requester_info `
    - `ticket_top_navigation`
3. Change Details Page
    - `change_sidebar`
4. Contact Details Page
    - `contact_sidebar `
5. New Ticket Page
    - `new_ticket_sidebar `
6. New Change Page
    - `new_change_sidebar `
7. Asset Details Page
    - `asset_sidebar `

2021-04-22 05:16 UTC, Saif-Shines requested changes
There are some non blocking suggestions if you plan to incorporate. Do you plan to incorporate them?

2021-04-22 05:16 UTC, Saif-Shines commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/styles/images/aeroplane.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 100 100"><text x="50%" y="50%" dominant-baseline="central" text-anchor="middle" font-size="64">✈️</text></svg>
I pick icons from this website. 

If you find aeroplane boring, you can pick an alternative one from here - https://formito.com/tools/favicon?ref=jonas.io

2021-04-22 05:16 UTC, Saif-Shines commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/styles/images/icon.svg
> +</svg>
I have noticed that this icon is no longer used for the app. You can safely delete this.

2021-04-25 11:24 UTC, teja-kummarikuntla commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/styles/images/aeroplane.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 100 100"><text x="50%" y="50%" dominant-baseline="central" text-anchor="middle" font-size="64">✈️</text></svg>
I tried with a few puppies. Nonetheless, Planes and Copters looks the best either.

2021-04-25 11:36 UTC, teja-kummarikuntla commented
> There are some non blocking suggestions if you plan to incorporate. Do you plan to incorporate them? Let me know if you plan to incorporate them in a next cycle or so. I will have this PR approved.

Yes, let me know, we can work that!

2021-04-26 04:09 UTC, Saif-Shines submitted a review, later dismissed

2021-05-05 09:57 UTC, ravirajsubramanian submitted a review, later dismissed

2021-05-05 09:57 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/asset_details_page/asset_sidebar.html
> +        return console.log(`asset sidebar location: app is activated 🥁`);
Please convert any console.log statement to console.info if they are important to understand the flow and console.error if they are for error handling.

2021-05-05 09:57 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/asset_details_page/asset_sidebar.html
> +</html>
Please add an empty line at the end of the file.

2021-05-06 04:34 UTC, Saif-Shines approved these changes
🏄‍♀️

2021-05-06 05:22 UTC, merged