Custom Iparams app built using Ember
freshworks/marketplace-sample-apps pull request #312
Opened 2021-04-23 06:21 UTC by arunrajkumar235

2021-04-23 17:38 UTC, ravirajsubramanian commented on Demo-Apps/README.md
> +| [freshchat-typescript-app](./freshchat-typescript-app) | An serverless app built using Typescript that calls a webhook on every product event. |
An serverless app -> A serverless app

2021-04-23 17:38 UTC, ravirajsubramanian commented on Demo-Apps/ember-iparams-app/README.md
> +Any changes you make to the Ember app's source files files will automatically trigger an Ember build and will be served locally when you run `yarn watch`.
files files -> files

2021-04-23 17:38 UTC, ravirajsubramanian commented on Demo-Apps/ember-iparams-app/packages/app/package.json
> +    "clean:config": "rimraf ./config/assets",
I think it's your custom alias for `rm -rf`. Could you please change it to the original command?

2021-04-23 17:38 UTC, ravirajsubramanian commented on Demo-Apps/ember-iparams-app/packages/iparams-ember/README.md
> +* `cd jaya`
I think these installation instructions will vary for the developers running the app from the marketplace sample apps repository.

2021-04-23 17:38 UTC, ravirajsubramanian commented on Demo-Apps/ember-iparams-app/packages/iparams-ember/package.json
> +    "clean": "rimraf ./dist ./tmp",
Could you replace `rimraf` alias with the original command?

2021-04-23 17:38 UTC, ravirajsubramanian commented on Demo-Apps/ember-iparams-app/packages/iparams-ember/README.md
> +# jaya
Is the name Jaya reference required? The sample app name is different. So, it would just be out of context for the users later visiting the repo.

2021-04-24 00:06 UTC, arunrajkumar235 commented on Demo-Apps/ember-iparams-app/packages/iparams-ember/README.md
> +# jaya
Removed the reference and cleaned up the file.

2021-04-24 00:09 UTC, arunrajkumar235 commented on Demo-Apps/ember-iparams-app/packages/iparams-ember/package.json
> +    "clean": "rimraf ./dist ./tmp",
`rm -rf` is a command that will not work on Windows machines. Hence, I'm making use of a package called `rimraf`. It is added as a dev dependency in packages.json.
`rimraf` will work irrespective of the OS it is running on.
I used this package assuming that not all marketplace app developers will own a Mac.

2021-04-24 00:09 UTC, arunrajkumar235 commented on Demo-Apps/ember-iparams-app/packages/iparams-ember/README.md
> +* `cd jaya`
Completely refactored this file. Removed unwanted references.

2021-04-24 00:09 UTC, arunrajkumar235 commented on Demo-Apps/ember-iparams-app/packages/app/package.json
> +    "clean:config": "rimraf ./config/assets",
`rm -rf` is a command that will not work on Windows machines. Hence, I'm making use of a package called `rimraf`. It is added as a dev dependency in packages.json.
`rimraf` will work irrespective of the OS it is running on.
I used this package assuming that not all marketplace app developers will own a Mac.

2021-04-24 00:10 UTC, arunrajkumar235 commented on Demo-Apps/ember-iparams-app/README.md
> +Any changes you make to the Ember app's source files files will automatically trigger an Ember build and will be served locally when you run `yarn watch`.
Done

2021-04-24 00:10 UTC, arunrajkumar235 commented on Demo-Apps/README.md
> +| [freshchat-typescript-app](./freshchat-typescript-app) | An serverless app built using Typescript that calls a webhook on every product event. |
Done

2021-04-24 08:21 UTC, Saif-Shines commented
Can we move this app folder to [Play-Along/Tutorials](https://github.com/freshworks/marketplace-sample-apps/tree/master/Play-Along/Tutorials ) directory? I suppose you'd also have a blog to link to. So that would be relevant place.

2021-04-24 08:25 UTC, Saif-Shines commented on Demo-Apps/ember-iparams-app/packages/app/README.md
> +Explore [more of app sample codes](https://github.com/freshworks/marketplace-sample-apps) on the Freshworks github respository.
I suppose the goal of this file to explain the app does. It is described well in ember-iparams-app/README.md file. Assuming it, this file is redundant can be deleted.

2021-04-24 08:34 UTC, Saif-Shines commented on Demo-Apps/ember-iparams-app/packages/app/app/template.html
> +    Ember Iparams Sample App
Our experience with newer developers taught us that, they don't usually understand `Iparams Sample App`. Can we say `Configuration page using Ember` does it convey the same thing that you intended?

2021-04-24 08:42 UTC, Saif-Shines commented on Demo-Apps/ember-iparams-app/packages/app/app/template.html
> +    Ember Iparams Sample App
App name to be `config-iparams-html-ember` would also make sense for a visitor setting right expectations. This is a pattern we are also trying to follow in some of [the sample apps](https://github.com/freshworks/marketplace-sample-apps/tree/master/Freshworks-Samples/App-Development-Features/Configuration-Features).

2021-04-24 09:22 UTC, Saif-Shines requested changes
Thank you for taking time and contributing to the repository. To make the contribution more powerful and reachable for the developers, I've added some comments those focus on understandability of this repo users.

2021-04-24 09:22 UTC, Saif-Shines commented on Demo-Apps/ember-iparams-app/packages/app/app/template.html
> +  <head></head>
The fact that `app` directory is inside of another `app` directory might be confusing. It is true that app platform requries the foldername to be `app` but, is there possiblity to rename `packages/app` instead of `packages/app/app` ?

2021-04-24 09:22 UTC, Saif-Shines commented on Demo-Apps/ember-iparams-app/packages/app/manifest.json
> +          "url": "template.html",
Please consider renaming `template.html` to `index.html`

We are just trying to follow the same from few weeks now. In the older templates it is true that cli used to generate `template.html`

2021-04-24 09:22 UTC, Saif-Shines commented on Demo-Apps/ember-iparams-app/packages/app/manifest.json
> +          "icon": "icon.svg"
Nice to have: 

We can actually use a different icon - https://formito.com/tools/favicon?ref=jonas.io

Just a nice to have thing from UX point of view. You might have to copy paste an emoji svg and change it's default size to 64px.

2021-04-24 09:22 UTC, Saif-Shines commented on Demo-Apps/ember-iparams-app/packages/iparams-ember/README.md
> +# iparams-ember
As a developer, when one opens app's root directory/README.md 

All the details of it are expected to be in the root directory's README.md. I am not sure if what is present already at the moment is abundant. If not do you think, root directory's README.md should reason and link to this README.md ? Or is this page redundant?

2021-04-24 09:22 UTC, Saif-Shines commented on Demo-Apps/ember-iparams-app/packages/iparams-ember/app/index.html
> +<!DOCTYPE html>
I assume,

1. Developer needs to  install all the dependences as mentioned in the prereqs.
2. Then what's in `iparams-ember` would be bundled as `assets` directory in `app/config/assets`

In that case, any first time developer might confuse with the folder name `iparams-ember`. To indicate that it's unbundled version of config page, shall we rename it to `unbundled-ember-page` or anything that's inline with above reasoning would be fine.

2021-04-24 09:22 UTC, Saif-Shines commented on Demo-Apps/ember-iparams-app/packages/iparams-ember/app/styles/app.scss
> +*,
You can include SCSS in the prereqs as well in the root README.md > Prerequisites.

2021-06-30 05:22 UTC, kaustavdm commented
@Saif-Shines @ravirajsubramanian Should we close this, or will this get merged soon?

2021-06-30 07:39 UTC, Saif-Shines commented
@kaustavdm - For apps like this one, I'd prefer to as a separate repository on `freshworks-developers` org where we could give repository access rights to @arunrajkumar235

2022-01-03 06:13 UTC, Saif-Shines commented
Temporarily closing this PR.

2022-01-03 06:13 UTC, closed without merging