newhire-onboarding-invites Freshteam Sample App
freshworks/marketplace-sample-apps pull request #313
Opened 2021-04-24 08:46 UTC by Hamsini-Sivalenka

On the event of newHireCreate in Freshteam, the app performs any of the following operations based on the new hire's department:
1. Send welcome mail - Using Sendgrid
2. Create aws account and add to sender's organisation
3. Send invite to BitBucket repository

Select which operations to perform for which department in the custom installation page.

2021-04-24 09:52 UTC, Saif-Shines requested changes
Nice work in the first attempt. 

From this perspective of developer readership in this repo, I've added couple of comments that might be more helpful.

2021-04-24 09:52 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/README.md
> +            └── onEmployeeCreate.json
Encourage you to use [common agreed template](https://github.com/freshworks/marketplace-sample-apps/blob/master/.github/PULL_REQUEST_TEMPLATE/APP_README_TEMPLATE.md) to paint a picture for code readers.

2021-04-24 09:52 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/README.md
> +## Freshteam App Project
Please use a more non-generic name to the app. Up to you.

2021-04-24 09:52 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/README.md
> +3. Send invite to BB repo
Describe your app assuming that an app user is trying to understand what your app does not from the lens of a developer trying to know how the app is built. That way it will any way benefit the later.

For example,

This app assumes the host Freshworks product to be Freshteam. An employee engagement software.

App observes if new empolyee has been hired and...
1. Sends a welcome email on new hire's email address.
2. Creates a AWS account and adds to Organisation.
3. Sends an invite to a configured BitBucket Repository 

_Hyperlink to sources whereever necessary_

2021-04-24 09:52 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/config/assets/iparams.css
> +    ---------------
Useful comment to understand grid layout for this file!

2021-04-24 09:52 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/config/iparam_test_data.json
> +{}
This file has been deprecated and is redundant. You can safely delete this file.

2021-04-24 09:52 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/config/iparams.html
> +            };
As a good practice, I would recommend you to use

1. Classes instead of IDs.
2. Make A,E,F,M,S or opA, opE.. so on to be renamed into something that's more understandable.

2021-04-24 09:52 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/manifest.json
> +  ]
This field is no longer required. You can remove it safely.

2021-04-24 09:52 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/server/lib/handle-response.js
> +};
I assume this is some sort of default file that is generated. If you are not using it, feel free to remove this file as well.

2021-04-24 09:52 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/server/server.js
> +    bitBucket(args);
This pattern of `if` statements may cause unexpected consequences. Although, it doesn't not effect this app or usecase very much in this particular scenario. Developer use this repository as reference may begin to use it various other places.

Please use `if.. else` statements as well.

Do consider renaming the paramenter `op` to `operation` or similar to make it more understandble.

2021-04-24 09:52 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/server/server.js
> +  sendG.setApiKey("YOUR SENDGRID API KEY HERE");
Consider capturing this detail from the configuration page. :)

2021-04-24 09:52 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/server/server.js
> +    `,
If you could move this text to seperate variable such as `const emailContent`, it would be easier for code readers to understand.

2021-04-24 09:52 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/server/server.js
> +    region: 'us-east-1'
Should region be a drop down in configuration page?

2021-04-24 09:52 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/server/server.js
> +    const opM = 6000025155; const opS = 6000025158;
Are these _IDs_ specific to each Freshteam account? If someone download this app in an another freshteam account, are these IDs still relavant?

2021-04-24 10:04 UTC, Hamsini-Sivalenka commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/server/server.js
> +    region: 'us-east-1'
No no, it has to be 'us-east-1' always

2021-04-24 10:06 UTC, Hamsini-Sivalenka commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/server/server.js
> +    const opM = 6000025155; const opS = 6000025158;
No, these IDs are account specific. I am not sure how to dynamically create html fields from a JSON object (I considered making a POST request to api/departments, which will return the department details available in that account). I am also not sure how we can alter the CSS file accordingly. I will work on this.

2021-06-01 03:48 UTC, Saif-Shines submitted a review, later dismissed
A lot of updates! Appreciate your work on this. I will approve from my end with a small comment.

2021-06-01 03:48 UTC, Saif-Shines commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/manifest.json
> +  ]
After an [security update](https://community.developers.freshworks.com/t/critical-security-update-to-the-platform-may-2021/2788/10) that went live in May, the platform team decided to bring back this `whitelisted domains` field.

I see the app is making API calls to `subdomain.freshteam.com`. We will need to add the same to the allow list.

2021-06-01 08:35 UTC, kaustavdm reviewed
Added a few review comments, which are mostly improvements on what you've already done. I must say excellent work @Hamsini-Sivalenka!

Beyond what I have added as comments, you might also consider having your text editor add an empty newline at the end of each file.

2021-06-01 08:35 UTC, kaustavdm commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/server/server.js
> +    var options = { headers: headers };
All of these variable declarations can be `const`, since you are not reassigning them.

2021-06-01 08:35 UTC, kaustavdm commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/server/server.js
> +    }
1. The `try...catch` statement here is unnecessary, since you are performing nested asynchronous operations within it. You should remove the `try...catch` statement and use the `$request.get(url, options).then[...]` directly.
2. This `resolve` part of `$request.get()` here is triggering multiple async operations (which is what `performOperations()` does) using a synchronous `for` loop. There is nothing wrong here. But, it can have side effects if you expect those async operations to _complete_ in the order they were started. I would recommend adding inline code comments here describing the intention.

2021-06-01 09:54 UTC, Hamsini-Sivalenka commented on Freshworks-Samples/App-Development-Features/Serverless-Features/external_events_app/server/test_data/onAppUninstall.json
> +  "event": "onTicketCreate",
Oh I didnt realise it was changed for this app. We found that changing the `event` while trying to simulate an event didn't work. For example: changing `event` to "onTicketCreate" while trying to simulate "onAppUninstall" would still simulate "onAppUninstall". I think "onAppUninstall" event changed to "onTicketCreate" here when we were testing this.

2021-06-02 11:30 UTC, ravirajsubramanian reviewed
Hi @Hamsini-Sivalenka,

Awesome work with this app.
I have left a few suggestions. Let me know if you have any queries.

Thanks for your contribution to the samples repository.

2021-06-02 11:30 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Serverless-Features/external_events_app/server/test_data/onAppUninstall.json
> +  "event": "onTicketCreate",
Could we change it back to `onAppUninstall` then?

2021-06-02 11:30 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Serverless-Features/external_events_app/server/test_data/onExternalEvent.json
> +}
You can configure in VS code to automatically add a new line to all the files to avoid these changes.

2021-06-02 11:30 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Serverless-Features/serverless_overview/serverless_with_multiple_events/server/test_data/onTicketCreate.json
> +  "event": "onTicketUpdate",
Could you change this also back to the original event based on the file name? You can keep only the used event's test data and remove the rest.

2021-06-02 11:30 UTC, ravirajsubramanian commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/config/iparams.html
> +            console.log(error);
Could you please add a descriptive error message before logging the error object?
Also, please use console.error() statement for logging the errors so they can be differentiated from the development logs.

2021-06-02 11:30 UTC, ravirajsubramanian commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/server/server.js
> +        console.log(
Please use console.info statment for logs in the success flow and console.error statements for failure flow.

2021-06-02 11:30 UTC, ravirajsubramanian commented on Freshworks-Samples/Freshteam/newhire-onboarding-invites/server/server.js
> +const AWS = require("aws-sdk");
Since aws-sdk is a bulk package and contains a lot of unnecessary parts for this application, [AWS Organizations client](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-organizations/index.html) which is a minimal version for this particular use can be used.

The `aws-sdk` will ideally fail to install in the production apps due to limited RAM available for the Serverless apps. Using the mentioned client make it light to get installed quickly.

2021-06-02 12:39 UTC, Hamsini-Sivalenka commented on Freshworks-Samples/App-Development-Features/Serverless-Features/external_events_app/server/test_data/onAppUninstall.json
> +  "event": "onTicketCreate",
yes, i'll change it back 👍

2021-06-14 10:28 UTC, ravirajsubramanian approved these changes
Good work, @Hamsini-Sivalenka. Thanks for addressing the review suggestions.

2021-06-14 10:43 UTC, merged