Tweak: Spinner in Joke component
freshworks/marketplace-sample-apps pull request #331
Opened 2021-05-11 12:24 UTC by teja-kummarikuntla

Tweaking Joke component in `full_page` location for apps
-  config-iparams-html-freshdesk
-  config-iparams-html-freshservice

Changes:
> Added a spinner during the API request and shown the card component once response received.

![cihf](https://user-images.githubusercontent.com/81623704/117813905-439fbf00-b281-11eb-8d45-36444a3b724d.gif)

2021-05-12 04:06 UTC, Saif-Shines commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshdesk/app/scripts/app.js
> +function q(selector) {
Shall we pick a more meaningful function name? - maybe `pick` or something that easier to understand?

2021-05-12 04:09 UTC, Saif-Shines requested changes
Adding single comment

2021-05-12 04:45 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshdesk/app/scripts/app.js
> +    punchline = JSON.parse(data.response).punchline;
It looks like the punchline variable is not defined anywhere before Is it defined here?

2021-05-12 04:45 UTC, ravirajsubramanian commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshdesk/app/scripts/app.js
> +      console.log(error);
Please add the reason for the error to the console log and use console.error statement.

2021-05-12 06:28 UTC, teja-kummarikuntla commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshdesk/app/scripts/app.js
> +    punchline = JSON.parse(data.response).punchline;
Yes @ravirajsubramanian , I'm using it globally as I needed it outside the function.
Tried returning the `punchline` value but getting messed up with promises.

And Btw, I've this one restless warning caused by `punchline`
<img width="566" alt="Screenshot 2021-05-12 at 11 55 56 AM" src="https://user-images.githubusercontent.com/81623704/117928539-54037880-b319-11eb-9b2c-3814edeb136e.png">

2021-05-13 16:23 UTC, kaustavdm requested changes
Good job, Teja. Minor tweaks here and there.

2021-05-13 16:23 UTC, kaustavdm commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshdesk/app/index.html
> +            <br />
Use CSS `margin-bottom` on `#setup` instead of `<br />`. Alternatively, create a generic class and reuse it for both `#setup` and `#punchline-btn`.

Something like:

```css
.space-below {
  margin-bottom: 1rem;
}
```

2021-05-13 16:23 UTC, kaustavdm commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshdesk/app/scripts/app.js
> +const JOKE_ENDPOINT = "https://official-joke-api.appspot.com/random_joke";
If `JOKE_ENDPOINT` is not used anywhere else apart from `getJoke()`, consider moving the variable within that function's scope.

2021-05-13 16:23 UTC, kaustavdm commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshservice/app/index.html
> +            <br />
See previous comment about using `margin` and replace `<br />`.

2021-05-13 16:23 UTC, kaustavdm commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshservice/app/scripts/app.js
> +const JOKE_ENDPOINT = "https://official-joke-api.appspot.com/random_joke";
See previous comment on moving variable into function scope if only that function is using this variable.

2021-05-13 16:23 UTC, kaustavdm commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshservice/app/styles/generics.css
> +  font-family: "Lucida Sans", "Lucida Grande";
I wonder if we can standardise the font family used in our examples. Lucida Sans is a MS specific font, isn't it?

2021-05-17 04:04 UTC, Saif-Shines submitted a review, later dismissed
No major comments from my end 👍🏼  

All seems good.

2021-05-18 07:56 UTC, teja-kummarikuntla commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshservice/app/styles/generics.css
> +  font-family: "Lucida Sans", "Lucida Grande";
Found these fonts being used in other examples, it looks decent with product fonts!

2021-05-18 11:17 UTC, Saif-Shines approved these changes

2021-05-18 14:27 UTC, kaustavdm requested changes
Minor tweaks needed, Teja. You can ignore the comment on using dependency injection. That is just FYI.

2021-05-18 14:27 UTC, kaustavdm commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshdesk/app/index.html
> +            ></fw-button>
This linebreak looks weird here. Consider removing it.

2021-05-18 14:27 UTC, kaustavdm commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshdesk/app/scripts/app.js
> +    let setup = JSON.parse(data.response).setup;
Looks like this variable can be a `const` since it is not reassigned.

2021-05-18 14:27 UTC, kaustavdm commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshservice/app/index.html
> +            ></fw-button>
Same weird line break. Make `</fw-icon>` on one line.

2021-05-18 14:27 UTC, kaustavdm commented on Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshdesk/app/scripts/app.js
> +    punchline = JSON.parse(data.response).punchline;
You can possibly explore dependency injection for the `punchline` variable. That makes it testable too. So, instead of making it a global, you can pass the variable to functions that need it.

That way, you avoid side-effects of manipulating a global variable.

This is not very important. It makes the code look better and more manageable.

2021-05-31 09:03 UTC, kaustavdm approved these changes
LGTM

2021-05-31 14:27 UTC, merged