[DEVREL-1153] feat(sentimental-jeff-app) update custom field
freshworks/marketplace-sample-apps pull request #332
Opened 2021-05-11 14:34 UTC by ravirajsubramanian

Update a custom ticket field with the sentiment analysis result

2021-05-12 07:00 UTC, kaustavdm requested changes
Woah. This is a complex PR. Excellent job though!

I've nitpicked some typos which you can change, and added some comments about using loops, which you can choose to act on. Code complexity is quite high in some functions. But looks like it does the job overall.

Some inline comments explaining what is happening would help anyone reading the code.

2021-05-16 07:46 UTC, ravirajsubramanian commented on Demo-Apps/sentimental_jeff_app/app/app.js
> +  nuetral: 'nuetral'
Changed, thanks for catching it. 😃

2021-05-16 07:46 UTC, ravirajsubramanian commented on Demo-Apps/sentimental_jeff_app/app/app.js
> +          notifyError('Failed to update sentiment result to the configed ticket field.')
Changed. 👍

2021-05-16 07:48 UTC, ravirajsubramanian commented on Demo-Apps/sentimental_jeff_app/app/app.js
>    }
Changed it the same way. The only change is `const` within the for loop will break in Firefox it seems. So, initializing the variable before the loop.

2021-05-17 03:59 UTC, Saif-Shines approved these changes
:)

2021-05-17 03:59 UTC, Saif-Shines commented on Demo-Apps/sentimental_jeff_app/README.md
> -| [`Request API`](https://developers.freshdesk.com/v2/docs/request-api/) | Request API has been used to get the conversational details |
I appreciate the not forgetting to update README following the enhancements to the app :)

2021-05-18 07:32 UTC, kaustavdm commented on Demo-Apps/sentimental_jeff_app/app/app.js
>    }
That's weird. You should still be able to use the `let` inside the `for` loop.

On looking up, I found [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1237395) filed, but looks like it was resolved years ago. I also tried `for...of` with `const` in Firefox console, and it worked.

<img width="345" alt="Screenshot 2021-05-18 at 1 01 54 PM" src="https://user-images.githubusercontent.com/364832/118610312-42b6e200-b7d9-11eb-884c-e27d13e7b6c4.png">

Can you see if you can reproduce this error on Firefox? If yes, see if you can bump up that thread in Bugzilla.

2021-05-18 07:34 UTC, kaustavdm submitted a review, later dismissed
Approving for now. But take a look at the `const` usage in `for..of`.

2021-06-01 13:54 UTC, ravirajsubramanian commented on Demo-Apps/sentimental_jeff_app/app/app.js
>    }
Just found until Firefox version 51, the issue existed and now fixed. Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#browser_compatibility

So, just avoided using it for a wider spectrum of support browser versions.

2021-06-03 08:12 UTC, Saif-Shines approved these changes

2021-06-08 11:30 UTC, merged