[DEVREL-1170] :adhesive_bandage: Fix: Borken Links | App-Dev-Features
freshworks/marketplace-sample-apps pull request #336
Opened 2021-05-14 12:20 UTC by teja-kummarikuntla

2021-05-14 12:33 UTC, teja-kummarikuntla reviewed
@Saif-Shines , I've pointed a few questions as reviews below, we can have another commit to fix them prior to merging.

2021-05-14 12:33 UTC, teja-kummarikuntla commented on Freshworks-Samples/App-Development-Features/README.md
>  [Custom Installation Page](https://medium.com/freshworks-developer-blog/updates-to-the-custom-installation-page-b787b66c8a39) | [Custom Installation page demo App](https://github.com/freshdesk/market
[Custom Installation Page](https://medium.com/freshworks-developer-blog/updates-to-the-custom-installation-page-b787b66c8a39), A few hyperlinks in this Blog content are broken

2021-05-14 12:33 UTC, teja-kummarikuntla commented on Freshworks-Samples/App-Development-Features/README.md
>  [Custom Installation Page](https://medium.com/freshworks-developer-blog/updates-to-the-custom-installation-page-b787b66c8a39) | [Custom Installation page demo App](https://github.com/freshdesk/market
> [Custom Installation page demo App](https://github.com/freshdesk/marketplace-sample-apps/tree/master/Freshdesk/v2/custom_installation_page_app) [BROKEN]

I'm unsure which app URL in the repo helps replacing, `config-iparams-json-freshdesk` and `config-iparams-html-freshdesk` are already used above

2021-05-17 03:40 UTC, Saif-Shines requested changes
Thanks for fixing this.

2021-05-17 03:40 UTC, Saif-Shines commented on Freshworks-Samples/App-Development-Features/README.md
>  [Custom Installation Page](https://medium.com/freshworks-developer-blog/updates-to-the-custom-installation-page-b787b66c8a39) | [Custom Installation page demo App](https://github.com/freshdesk/market
Can we say, Build configuration pages using HTML or JSON? 

Where HTML and JSON will by hyperlinked to respective apps in the repository?

2021-05-18 07:36 UTC, Saif-Shines approved these changes

2021-05-18 07:39 UTC, kaustavdm commented
Just saying, I love that the title says, "borken links". It's very doge. :-D

2021-05-18 07:45 UTC, merged